on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [13]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Run Test
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm test