name: vscode-test
on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: yarn --frozen-lockfile
      name: Install Dependencies
      - run: yarn electron x64
      name: Download Electron
      - run: yarn gulp hygiene
      name: Run Hygiene Checks
      - run: yarn monaco-compile-check
      name: Run Monaco Editor Checks
      - run: yarn valid-layers-check
      name: Run Valid Layers Checks
      - run: yarn compile
      name: Compile Sources
      - run: yarn download-builtin-extensions
      - run: npm install
      name: run test
      - run: npm test